spring:
  datasource:
    generate-unique-name: false
    name: oliveiratrade

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
